from pydantic import BaseModel, Field
from typing import List


class YachtData(BaseModel):
    LOA_FT: str = ""
    LOA_IN: str = ""
    LOA_M: str = ""

    LWL_FT: str = ""
    LWL_IN: str = ""
    LWL_M: str = ""

    YEAR: str = ""
    REFIT: str = ""
    BUILDER: str = ""
    GT: str = ""
    STATEROOMS: str = ""
    GUESTS: str = ""
    CREW: str = ""

    BEAM_FT: str = ""
    BEAM_IN: str = ""
    BEAM_M: str = ""

    MAX_DRAFT_FT: str = ""
    MAX_DRAFT_IN: str = ""
    MAX_DRAFT_M: str = ""
    
    MIN_DRAFT_FT: str = ""
    MIN_DRAFT_IN: str = ""
    MIN_DRAFT_M: str = ""
    
    YACHT_TYPE: str = ""
    YACHT_SUBTYPE: str = ""
    MODEL: str = ""
    HULL_NUMBER: str = ""
    HULL_MATERIAL: str = ""
    HULL_COLOR: str = ""
    HULL_CONFIGURATION: str = ""
    SUPERSTRUCTURE_MATERIAL: str = ""
    RIG_TYPE: str = ""
    BUILD_TYPE: str = ""
    EXTERIOR_DESIGNER: str = ""
    INTERIOR_DESIGNER: str = ""
    REFIT_EXTERIOR_DESIGNER: str = ""
    REFIT_INTERIOR_DESIGNER: str = ""
    NAVAL_ARCHITECT: str = ""
    CONVERSION_YEAR: str = ""
    NET_TONNAGE: str = ""

    MAX_SPEED: str = ""
    CRUISE_SPEED: str = ""
    ECONOMICAL_SPEED: str = ""
    MAX_RANGE: str = ""
    CRUISE_RANGE: str = ""
    ECONOMICAL_RANGE: str = ""

    CRUISING_CONSUMPTION_L: str = ""
    CRUISING_CONSUMPTION_GAL: str = ""
    ECONOMICAL_CONSUMPTION_L: str = ""
    ECONOMICAL_CONSUMPTION_GAL: str = ""

    DISPLACEMENT_NOTES: str = ""
    FULL_DISPLACEMENT: str = ""
    HALF_LOAD_DISPLACEMENT: str = ""
    LIGHT_LOAD_DISPLACEMENT: str = ""

    FUEL_L: str = ""
    FUEL_GAL: str = ""
    FRESH_WATER_L: str = ""
    FRESH_WATER_GAL: str = ""
    LUBE_OIL_L: str = ""
    LUBE_OIL_GAL: str = ""
    BLACK_WATER_HOLDING_TANK_L: str = ""
    BLACK_WATER_HOLDING_TANK_GAL: str = ""
    GREY_WATER_HOLDING_TANK_L: str = ""
    GREY_WATER_HOLDING_TANK_GAL: str = ""
    WASTE_OIL_L: str = ""
    WASTE_OIL_GAL: str = ""

    IACS_SOCIETY: str = ""
    MMSI: str = ""
    IMO: str = ""
    FLAG: str = ""
    REGISTRY_PORT: str = ""
    COMMERCIAL_COMPLIANCE: str = ""

    ENGINE_1_MAKE: str = ""
    ENGINE_1_MODEL: str = ""
    ENGINE_1_TYPE: str = ""
    ENGINE_1_FUEL_TYPE: str = ""
    ENGINE_1_OUTPUT_HP: str = ""
    ENGINE_1_HOURS: str = ""
    ENGINE_1_DATE: str = ""
    ENGINE_1_LOCATION: str = ""

    ENGINE_2_MAKE: str = ""
    ENGINE_2_MODEL: str = ""
    ENGINE_2_TYPE: str = ""
    ENGINE_2_FUEL_TYPE: str = ""
    ENGINE_2_OUTPUT_HP: str = ""
    ENGINE_2_HOURS: str = ""
    ENGINE_2_DATE: str = ""
    ENGINE_2_LOCATION: str = ""

    ENGINE_3_MAKE: str = ""
    ENGINE_3_MODEL: str = ""
    ENGINE_3_TYPE: str = ""
    ENGINE_3_FUEL_TYPE: str = ""
    ENGINE_3_OUTPUT_HP: str = ""
    ENGINE_3_HOURS: str = ""
    ENGINE_3_DATE: str = ""
    ENGINE_3_LOCATION: str = ""

    ENGINE_4_MAKE: str = ""
    ENGINE_4_MODEL: str = ""
    ENGINE_4_TYPE: str = ""
    ENGINE_4_FUEL_TYPE: str = ""
    ENGINE_4_OUTPUT_HP: str = ""
    ENGINE_4_HOURS: str = ""
    ENGINE_4_DATE: str = ""
    ENGINE_4_LOCATION: str = ""

    GENERATOR_1_MAKE: str = ""
    GENERATOR_1_MODEL: str = ""
    GENERATOR_1_TYPE: str = ""
    GENERATOR_1_FUEL_TYPE: str = ""
    GENERATOR_1_OUTPUT: str = ""
    GENERATOR_1_HOURS: str = ""
    GENERATOR_1_DATE: str = ""
    GENERATOR_1_LOCATION: str = ""

    GENERATOR_2_MAKE: str = ""
    GENERATOR_2_MODEL: str = ""
    GENERATOR_2_TYPE: str = ""
    GENERATOR_2_FUEL_TYPE: str = ""
    GENERATOR_2_OUTPUT: str = ""
    GENERATOR_2_HOURS: str = ""
    GENERATOR_2_DATE: str = ""
    GENERATOR_2_LOCATION: str = ""

    GENERATOR_3_MAKE: str = ""
    GENERATOR_3_MODEL: str = ""
    GENERATOR_3_TYPE: str = ""
    GENERATOR_3_FUEL_TYPE: str = ""
    GENERATOR_3_OUTPUT: str = ""
    GENERATOR_3_HOURS: str = ""
    GENERATOR_3_DATE: str = ""
    GENERATOR_3_LOCATION: str = ""

    GENERATOR_4_MAKE: str = ""
    GENERATOR_4_MODEL: str = ""
    GENERATOR_4_TYPE: str = ""
    GENERATOR_4_FUEL_TYPE: str = ""
    GENERATOR_4_OUTPUT: str = ""
    GENERATOR_4_HOURS: str = ""
    GENERATOR_4_DATE: str = ""
    GENERATOR_4_LOCATION: str = ""

    STABILIZER_MANUFACTURER: str = ""
    STABILIZER_MODEL: str = ""
    STABILIZER_TYPE: str = ""
    STABILIZER_SPEED: str = ""

    HELICOPTER: str = ""
    LIFT_CAPABLE: str = ""
    WHEELCHAIR_ACCESSIBLE: str = ""

    BOW_THRUSTER: str = ""
    STERN_THRUSTER: str = ""
    STEERING: str = ""
    SHAFTS_PROPELLERS: str = ""
    SHORE_POWER: str = ""
    GEARBOX: str = ""

    ELECTRICITY_BULLETS: List[str] = Field(default_factory=list)
    BATTERIES_BULLETS: List[str] = Field(default_factory=list)
    BATTERY_CHARGERS_BULLETS: List[str] = Field(default_factory=list)
    AIR_CONDITIONING_BULLETS: List[str] = Field(default_factory=list)
    OTHER_MACHINERY_BULLETS: List[str] = Field(default_factory=list)
